# Generated by Django 4.1.7 on 2023-02-25 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspaper',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='redactors',
            field=models.ManyToManyField(related_name='newspapers', to=settings.AUTH_USER_MODEL),
        ),
    ]
